export const PHOTO_LOAD = 'PHOTO_LOAD'

export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON'
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF'

export const ERROR_DISPLAY_ON = 'ERROR_DISPLAY_ON'
export const ERROR_DISPLAY_OFF = 'ERROR_DISPLAY_OFF'

export const USER_JOIN = 'USER_JOIN'
export const USER_LEAVE = 'USER_LEAVE'
export const USERS_LOAD = 'USERS_LOAD'

export const NEW_MESSAGE = 'NEW_MESSAGE'